image: registry.znuny.com/znuny/docker-otrs6ci:latest

stages:
  - test

mysql:
  stage: test
  services:
    - name: registry.znuny.com/znuny/docker-mysql-utf8:latest
      alias: mysql
  script:
    - /run.sh
    - su -c "perl /opt/otrs/bin/otrs.Console.pl Znuny4OTRS::AdvancedPackageManager::InstallSOPM /opt/otrs/Znuny4OTRS-OutOfOfficeFilter.sopm" -s /bin/bash otrs
    - su -c "perl /opt/otrs/bin/otrs.Console.pl Dev::UnitTest::Run --verbose --test Znuny4OTRSOutOfOfficeFilter/System/PostMaster/Filter/PreZnuny4OTRSOutOfOfficeFilter" -s /bin/bash otrs
    - su -c "perl /opt/otrs/bin/otrs.Console.pl Dev::UnitTest::Run --verbose --test Znuny4OTRSOutOfOfficeFilter/var/packagesetup/Znuny4OTRSOutOfOfficeFilter" -s /bin/bash otrs